#!/usr/bin/env node
/* Builds the single-file edition of T10 World.
 *
 *   node t10/build.js
 *
 * Reads t10/index.html, inlines every <script src="src/*.js"> in order, and
 * writes t10.html at the repo root. The result has no external requests at
 * all, so it plays straight off the filesystem.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const here = __dirname;
const src = path.join(here, 'index.html');
const out = path.join(here, '..', 't10.html');

let html = fs.readFileSync(src, 'utf8');

const tag = /[ \t]*<script src="(src\/[^"]+)"><\/script>\r?\n?/g;
const files = [];
html = html.replace(tag, (_, rel) => {
  const file = path.join(here, rel);
  let code = fs.readFileSync(file, 'utf8').replace(/\s*$/, '');
  // a literal </script> inside a string would close the tag early
  if (/<\/script/i.test(code)) code = code.replace(/<\/script/gi, '<\\/script');
  files.push(rel);
  return '<script>\n/* ===== ' + rel + ' ===== */\n' + code + '\n</script>\n';
});

if (!files.length) {
  console.error('build: no <script src="src/..."> tags found in index.html');
  process.exit(1);
}

html = html.replace(
  '<title>T10 WORLD</title>',
  '<title>T10 WORLD</title>\n<!-- Single-file build. Generated by t10/build.js from t10/index.html + t10/src/*.js — edit those, not this. -->'
);

fs.writeFileSync(out, html);
console.log('built ' + path.relative(path.join(here, '..'), out) +
  ' (' + (Buffer.byteLength(html) / 1024).toFixed(0) + ' KB) from ' + files.length + ' modules:');
files.forEach(f => console.log('  ' + f));
