import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import http from 'http'; import fs from 'fs'; import path from 'path';
const ROOT = path.resolve('.');
const TYPES={'.html':'text/html','.js':'text/javascript'};
const server=http.createServer((req,res)=>{const u=decodeURIComponent(req.url.split('?')[0]);
  fs.readFile(path.join(ROOT,u==='/'?'/index.html':u),(e,d)=>{if(e){res.writeHead(404);return res.end();}
  res.writeHead(200,{'Content-Type':TYPES[path.extname(u)]||'application/octet-stream'});res.end(d);});});
await new Promise(r=>server.listen(0,r)); const port=server.address().port;
const browser=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
  args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-sandbox','--disable-dev-shm-usage']});
const page=await browser.newPage({viewport:{width:1280,height:760}});
page.on('pageerror',e=>console.log('>>> '+e.message.slice(0,300)));
const SHOT=process.env.SHOTDIR||'/tmp/showcase'; fs.mkdirSync(SHOT,{recursive:true});
await page.goto(`http://127.0.0.1:${port}/index.html`,{waitUntil:'load'});
await page.waitForTimeout(1200);
await page.click('#t10-start'); await page.waitForTimeout(2600);
await page.screenshot({path:SHOT+'/creator.png'});
await page.evaluate(()=>{[...document.querySelectorAll('.t10-creator-btn')].find(x=>x.classList.contains('primary')).click();});
await page.waitForFunction(()=>window.__t10&&window.__t10.phase==='playing',{timeout:240000});
await page.waitForTimeout(9000);
// Settle into a good daytime spot with people around
await page.evaluate(()=>{const g=window.__t10;
  g.t10.handle('T10 set the time to 15'); g.t10.handle('T10 make it fair');
  g.t10.handle('T10 make the streets packed'); g.t10.handle('T10 heavy traffic');
  g.player.frozen=false; g.player.getUpTimer=0; g.player.human.animator.setState('idle');
  g.player.setCameraMode('third');
});
await page.waitForTimeout(16000);
await page.screenshot({path:SHOT+'/01-day-street.png'});
await page.evaluate(()=>{ const g=window.__t10; g.player.setCameraMode('first'); });
await page.waitForTimeout(2500);
await page.screenshot({path:SHOT+'/02-first-person.png'});
await page.evaluate(()=>{ const g=window.__t10; g.player.setCameraMode('third');
  g.t10.handle('T10 put me on a roof'); });
await page.waitForTimeout(7000);
await page.screenshot({path:SHOT+'/03-rooftop.png'});
await page.evaluate(()=>{ const g=window.__t10;
  g.t10.handle('T10 take me to the beach'); g.t10.handle('T10 make it golden hour'); });
await page.waitForTimeout(11000);
await page.screenshot({path:SHOT+'/04-beach.png'});
await page.evaluate(()=>{ const g=window.__t10;
  g.t10.handle('T10 take me to downtown'); g.t10.handle('T10 make it night'); g.t10.handle('T10 make it rain'); });
await page.waitForTimeout(13000);
await page.screenshot({path:SHOT+'/05-night-rain.png'});
await page.evaluate(()=>{ const g=window.__t10; g.t10.handle('T10 make it noon'); g.t10.handle('T10 clear the sky');
  g.t10.handle('T10 give me a sports car'); });
await page.waitForTimeout(4000);
await page.evaluate(()=>{ window.__t10.doVehicleToggle(); window.__t10.player.setCameraMode('first'); });
await page.waitForTimeout(3000);
await page.screenshot({path:SHOT+'/06-car-interior.png'});
await page.evaluate(()=>{ window.__t10.player.setCameraMode('third'); });
await page.waitForTimeout(2000);
await page.screenshot({path:SHOT+'/07-car.png'});
console.log('done');
await browser.close(); server.close();
